baseURL: "https://b.oldhu.com/"
disablePathToLower: true
languageCode: en-us
title: OLDHU's
theme: terminal
enableRobotsTXT: true
hasCJKLanguage: true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate: 5              # Number of articles displayed on the homepage  # 首页每页显示的文章数
disqusShortname: "oldhu"
params:
  themeColor: "green"
  contentTypeName: "content/post"
  description: "Post.order(\"created_at DESC\")"
  GithubID: "tiejunhu"
  TwitterID: "oldhuhu"
  LinkedInID: "oldhu"
  AnalyticsID: "UA-9830681-1"
  centerTheme: true
  mathjax: true
  tags: true
  logo:
    logoText: "OLDHU's"
languages:
  en:
    languageName: "English"
    title: "OLDHU's"
    subtitle: "A simple, retro theme for Hugo"
    copyright: "© 2022 oldhu"
    menuMore: "Show more"
    readMore: "Read more"
    readOtherPosts: "Read other posts"
    newerPosts: "Newer posts"
    olderPosts: "Older posts"
    missingContentMessage: "Page not found..."
    missingBackButtonLabel: "Back to home page"
taxonomies:
    category: "categories"
    series: "series"
    tag: "tags"