baseURL: "https://b.oldhu.com/"
disablePathToLower: true
languageCode: en-us
title: oldhu's 
theme: ink
enableRobotsTXT: true
hasCJKLanguage: true    
paginate: 6            

pygmentsstyle: "vs"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
services:
  disqus:
    shortname: "oldhu"

params:
  avatar: /images/avatar.jpeg
  social:
    -
      name: "Github"
      icon: "github"
      url: "https://github.com/tiejunhu"
    -
      name: "RSS"
      icon: "rss"
      url: /index.xml
  contentTypeName: "content/post"
  description: "Post.order(\"created_at DESC\")"
  GithubID: "tiejunhu"
  TwitterID: "oldhuhu"
  LinkedInID: "oldhu"
  AnalyticsID: "UA-9830681-1"
  centerTheme: true
  mathjax: true
  tags: true

disableKinds:
  - taxonomy
  - term

taxonomies:
    category: "categories"
    series: "series"

security:
  funcs:
    getenv:
      - ^VERCEL_
