baseURL: "https://b.oldhu.com/"
disablePathToLower: true
languageCode: en-us
title: oldhu's blog
theme: ink
enableRobotsTXT: true
hasCJKLanguage: true    
paginate: 5            
disqusShortname: "oldhu"

pygmentsstyle: "emacs"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

params:
  avatar: https://s.gravatar.com/avatar/bf653b87588f6bf74e65ee574dc65eab?s=256
  mode: auto
  social:
    -
      name: "Github"
      icon: "github"
      url: "https://github.com/tiejunhu"
    -
      name: "RSS"
      icon: "rss"
      url: /index.xml
  contentTypeName: "content/post"
  description: "Post.order(\"created_at DESC\")"
  GithubID: "tiejunhu"
  TwitterID: "oldhuhu"
  LinkedInID: "oldhu"
  AnalyticsID: "UA-9830681-1"
  centerTheme: true
  mathjax: true
  tags: true
taxonomies:
    category: "categories"
    series: "series"
    tag: "tags"
